import { SetMetadata } from '@nestjs/common';

export enum RouteActions {
  CREATE_PERMISSION = 'CREATE_PERMISSION',
  DELETE_PERMISSION = 'DELETE_PERMISSION',
  UPDATE_PERMISSION = 'UPDATE_PERMISSION',
  EDIT_PERMISSION = 'EDIT_PERMISSION',
  GET_ALL_PERMISSIONS = 'GET_ALL_PERMISSIONS',
  GET_BY_ID_PERMISSION = 'GET_BY_ID_CATEGORY',

  CREATE_COMPANY = 'CREATE_COMPANY',
  DELETE_COMPANY = 'DELETE_COMPANY',
  UPDATE_COMPANY = 'UPDATE_COMPANY',
  EDIT_COMPANY = 'EDIT_COMPANY',
  GET_ALL_COMPANIES = 'GET_ALL_COMPANIES',
  GET_BY_ID_COMPANY = 'GET_BY_ID_COMPANY',

  CREATE_TRANSACTION = 'CREATE_TRANSACTION',
  DELETE_TRANSACTION = 'DELETE_TRANSACTION',
  UPDATE_TRANSACTION = 'UPDATE_TRANSACTION',
  EDIT_TRANSACTION = 'EDIT_TRANSACTION',
  GET_ALL_TRANSACTIONS = 'GET_ALL_TRANSACTIONS',
  GET_BY_ID_TRANSACTION = 'GET_BY_ID_TRANSACTION',

  CREATE_COUNT = 'CREATE_COUNT',
  DELETE_COUNT = 'DELETE_COUNT',
  UPDATE_COUNT = 'UPDATE_COUNT',
  EDIT_COUNT = 'EDIT_COUNT',
  GET_ALL_COUNTS = 'GET_ALL_COUNTS',

  GET_BY_ID_COUNT = 'GET_BY_ID_COUNT',
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  DELETE_CATEGORY = 'DELETE_CATEGORY',
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  EDIT_CATEGORY = 'EDIT_CATEGORY',
  GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES',
  GET_BY_ID_CATEGORY = 'GET_BY_ID_CATEGORY',
}

export const ACTION_KEY = 'action';
export const RouteAction = (action: RouteActions) => {
  return SetMetadata(ACTION_KEY, action);
};
