name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install, lint, build 🔧
        run: |
          echo: $SECRET_KEY
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY}}
