name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install, lint, build 🔧
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY}}
        if: [$SECRET_KEY == 'test4']
        run: |
          echo: 'test4 - got secret'
